version: '2'

services:
  frontend: 
    build:
      context: ../app/src/CollAction/frontend
      dockerfile: Dockerfile.local

  backend: 
    build: 
      context: ../app/src
      dockerfile: Dockerfile.local
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    command: ["./wait-for-it.sh", "db:5432", "--", "dotnet", "run"]

  db:
    image: postgres
    environment:
      - POSTGRES_USER=collaction
    ports:
      - "5432:5432"
